---
# tasks file for protobuf

- name: install required packages
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - gcc-c++

- name: check if already installed
  stat: path={{ protobuf_prefix }}/lib
  register: protobuf_dir
  changed_when: protobuf_dir.stat.exists == False

- include: install.yml
  when: protobuf_dir.stat.exists == False

- name: clean downloaded file
  file: path={{ item }} state=absent
  with_items:
    - /tmp/protobuf-{{ protobuf_version }}
    - /tmp/protobuf-{{ protobuf_version }}.tar.gz
